### ISSUE TITLE
GHCJS Text encoding

### ISSUE THREAD

**Issue by saulzar** [Quid2/flat#13]
Like the comment says - this causes problems with GHCJS, especially in the reflex-platform where Text uses the underlying javascript string type. Is there a version of this which can avoid the text internals?

-- PROB: Not compatible with GHCJS
-- | Encode text as UTF16 and encode the result as an array of bytes
-- Efficient, as Text is already internally encoded as UTF16.  
eUTF16F :: T.Text -> Prim
eUTF16F t = eFillerF >=> eUTF16F_ t
  where
    eUTF16F_ !(TI.Text (TA.Array array) w16Off w16Len) s = writeArray array (2 * w16Off) (2 * w16Len) (nextPtr s)

**Comment by tittoassini** [comment]
Version 0.4 and upward should work fine using the UTF8 encoding, that is the default for Text.
