### ISSUE TITLE
Compile errors under base-4.13

### ISSUE THREAD

**Issue by patrickt** [Quid2/flat#15]
Since `fail` is no longer a member of Monad, you get this:

```
src/Data/Flat/Decoder/Types.hs:103:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
103 |     fail msg = Get $ \end s -> badEncoding end s msg
    |     ^^^^
```

**Comment by tittoassini** [comment]
Thanks, I will release a fixed version in a few days.

**Comment by Boarders** [comment]
Would it be possible to get a release with this fix to hackage?

**Comment by tittoassini** [comment]
Sorry for the delay, it will be released in a few days (I know that I said it before but THIS time it might actually be true).

**Comment by tittoassini** [comment]
The new version 0.4 fixes the problem.
