### ISSUE TITLE
'instance Flat Day' reports errors.

### ISSUE THREAD

**Issue by highfly22** [Quid2/flat#2]
```
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}

import Data.Flat
import Data.Time

instance Flat Day
```

```
error:
    • No instance for (Data.Flat.Class.GEncode (Rep Day))
        arising from a use of ‘Data.Flat.Class.$dmencode’
    • In the expression: Data.Flat.Class.$dmencode @Day
      In an equation for ‘encode’:
          encode = Data.Flat.Class.$dmencode @Day
      In the instance declaration for ‘Flat Day’
```

**Comment by tittoassini** [comment]
To automatically derive a Flat instance for a data type, the data type must be an instance of Generic.

Unfortunately, this is not the case for Day.

**Comment by unhammer** [comment]
See https://github.com/fpco/store/blob/247f2863bed0f5c1003ab835075b6dcafb9aa773/src/Data/Store/Internal.hs#L669 for an instance of `Day` for `store` – I suppose it'd be something like (completely untested) `size = Data.Flat.Encoder.Size.sInteger
encode = Data.Flat.encode (Time.toModifiedJulianDay d)
decode = Time.ModifiedJulianDay <$> Data.Flat.decode`

**Comment by kk-hainq** [comment]
Is there anything I can help with to make `flat-orphans` possible? Will anyone support the idea?
