### ISSUE TITLE
Roundtrip failure for `[AsArray [Int]]` 

### ISSUE THREAD

**Issue by DavidEichmann** [Quid2/flat#23]
This property fails: `unflat @[AsArray [Int]] (flat (x :: [AsArray [Int]])) == Right x`. I expect it to be true. here is a unit test case: `x = [AsArray [1..3], AsArray [4..8]]`

**Comment by DavidEichmann** [comment]
Note that the property holds when using `AsList` instead of `AsArray`

**Comment by bezirg** [comment]
Hoping it would further help to catch the bug:
When using `Int`, it returns:

```
> tst $ [AsArray [(1::Int)..3], AsArray [4..8]]
(False,99,[129,1,2,3,0,65,2,2,131,3,132,0,0])
```

When using `Word8`, it returns:

```
> tst $ [AsArray [(1::Word8)..3], AsArray [4..8]]
(False,99,*** Exception: src/Flat/Bits.hs:50:7-72: Non-exhaustive patterns in Right (PostAligned _ f)
```

**Comment by tittoassini** [comment]
Thanks for your help and apologies for the monstrous delay in addressing this issue.

It should now be sorted (in github and soon in the 0.5 release).

It was due to a caching issue that occasionally caused the number of array elements to be overwritten incorrectly.
