### ISSUE TITLE
Minor errors in Haddock comments.

### ISSUE THREAD

**Issue by kwxm** [Quid2/flat#31]
The Haddock for [`dBEBits32`](https://hackage.haskell.org/package/flat-0.4.4/docs/Flat-Decoder.html#v:dBEBits32) says
> Return the n most significant bits (up to maximum of 8) The bits are returned right shifted.

Presumably that should say 32 instead of 8, and similarly for `dBEBits64`.

**Comment by tittoassini** [comment]
Indeed! 

Now is fixed, thanks.
