### ISSUE TITLE
IntMap instance?

### ISSUE THREAD

**Issue by tysonzero** [Quid2/flat#9]
It would not require an extra dependency so I think it's definitely worth adding.

**Comment by tysonzero** [comment]
Instances for the `linear` library would also be fantastic, but I realize that does require another dependency.

**Comment by tittoassini** [comment]
As they say: better late than never :-)

In the latest version (0.4) I have added support for most data types in the packages that flat depends on: array, base, bytestring, containers, dlist, text, unordered-containers, vector

So now IntMap is covered :-)
